### ISSUE TITLE
Duplicate script - string copying issue

### ISSUE THREAD

**Issue by marc-weber1** [iPlug2/iPlug2#467]
**Describe the bug**
The python script does not recognize the encoded characters at the beginning of .sln files and various visual studio files in projects/ - this appears to be because they are encoded in UTF-8-BOM, and the python script does not recognize this encoding because it is using python 2 compatible libraries.

**To Reproduce**
Call duplicate.py on IPlugEffect, on windows, with python 3.7.3, on a newly cloned repository

**Trace**
```Traceback (most recent call last):
  File "duplicate.py", line 249, in <module>
    main()
  File "duplicate.py", line 230, in main
    for dir in dirwalk(outputpath, inputprojectname, outputprojectname, "AcmeInc", manufacturer, oldroot, newroot):
  File "duplicate.py", line 121, in dirwalk
    for x in dirwalk(fullpath, searchproject, replaceproject, searchman, replaceman, oldroot, newroot):
  File "duplicate.py", line 132, in dirwalk
    replacestrs(fullpath, searchproject, replaceproject)
  File "duplicate.py", line 73, in replacestrs
    for line in fileinput.input(files,inplace=1):
  File "C:\Users\facade\AppData\Local\Programs\Python\Python37-32\lib\fileinput.py", line 252, in __next__
    line = self._readline()
  File "C:\Users\facade\AppData\Local\Programs\Python\Python37-32\lib\fileinput.py", line 366, in _readline
    return self._readline()
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
```

**Suggested Fix**
Reencode all .sln and .vcxproj files in the repository from UTF-8-BOM to UTF-8 (make sure this doesn't interfere with visual studio and that visual studio doesn't reset the encoding), or use open() instead of fileinput (may require python 2 incompatibility). I can confirm that reencoding all the files works, however I do not use visual studio, so I can't test if it's a stable fix.

**Comment by olilarkin** [comment]
thanks, i'm thinking we should probably move to require python3

**Comment by olilarkin** [comment]
Scripts are all updated for Python3 @marc-weber1 can you confirm if this is still a problem?

**Comment by marc-weber1** [comment]
Same error; you might have to switch the fileinput calls to open() calls, or force the fileinput call to use UTF-8 instead of cp932:
```73 | fileinput.input(filename, openhook=fileinput.hook_encoded("utf-8"))```
Or the sln files might still just need to be converted from UTF-8-BOM to UTF-8 with something like notepad++.

**Comment by olilarkin** [comment]
with python3.8 installed from windows store, i don't get this issue "UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence" 

The duplicated VS project opens up fine. Not sure what the issue might be here

**Comment by olilarkin** [comment]
what shell are you using to call duplicate.py ?

**Comment by olilarkin** [comment]
is there a possibility you have a binary file in there which it is trying to duplicate?

**Comment by marc-weber1** [comment]
No, this was on a fresh clone of the repository. Python version is 3.8.5, and it was downloaded off the site; should be the 64-bit version. I can look into the problem again later because I think I found what the problem was, and maybe push a fix.

**Comment by poobool-koon** [comment]
I met the same error. And I modify code "duplicate.py" like below.
![image](https://user-images.githubusercontent.com/60247136/154625095-ec656aeb-9bb5-4160-a8d6-f834a8f8bb85.png)
Then the problem has resolved.
I guess the error occurs from difference of encoding that os uses.
